### ISSUE TITLE
What is needed from chemaxon?

### ISSUE THREAD

**Issue by UnixJunkie** [Laboratoire-de-Chemoinformatique/Reaction_Data_Cleaning#4]
Hello,

What is needed to install from chemaxon?
What is the exact product name?

Is there some class path setup or something else needed?

Can I run those scripts from Linux?

Thanks a lot,
F.

**Comment by UnixJunkie** [comment]
```bash
Reaction_Data_Cleaning# python3 ./scripts/standardizer.py 
Traceback (most recent call last):
  File "/home/berenger/src/Reaction_Data_Cleaning/./scripts/standardizer.py", line 591, in <module>
    standardizer = Standardizer(skip_errors=args.skipErrors, log_file=args.logFile,
  File "/home/berenger/src/Reaction_Data_Cleaning/./scripts/standardizer.py", line 62, in __init__
    Standardizer = autoclass('chemaxon.standardizer.Standardizer')
  File "/home/berenger/.local/lib/python3.9/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: chemaxon/standardizer/Standardizer java.lang.NoClassDefFoundError
```

**Comment by UnixJunkie** [comment]
Maybe this solves the problem:
```bash
python3 ./scripts/standardizer.py --jchem_path /opt/chemaxon/jchemsuite/lib/jchem.jar --help
```
